version: "3"

tasks:
  dev:
    cmds:
      - docker compose up -d
  stop:
    cmds:
      - docker compose stop
  down:
    cmds:
      - docker compose down
  logs:
    cmds:
      - docker compose logs
  migration:create:
    cmds:
      - bunx --bun drizzle-kit generate
  migration:drop:
    cmds:
      - bunx --bun drizzle-kit drop
  migration:run:
    cmds:
      - bunx --bun drizzle-kit migrate
  migration:snapshots:
    cmds:
      - bunx --bun drizzle-kit up
